В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [3]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [4]:
z = np.array([-2, -1, 0, 1, 2])

result = sigmoid(z)

print("Вхідні значення z:", z)
print("Значення сигмоїди:", result)

Вхідні значення z: [-2 -1  0  1  2]
Значення сигмоїди: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [5]:
def hypothesis(theta, X):
    z = np.dot(X, theta)
    return sigmoid(z)

theta = np.array([0.5, -0.5])

X = np.array([
    [1, 1],
    [1, -1],
    [1, 0],
    [1, 2]
])

h = hypothesis(theta, X)

print("Матриця X:\n", X)
print("Параметри theta:", theta)
print("\nРезультат гіпотези h_theta(X):")
print(h)

Матриця X:
 [[ 1  1]
 [ 1 -1]
 [ 1  0]
 [ 1  2]]
Параметри theta: [ 0.5 -0.5]

Результат гіпотези h_theta(X):
[0.5        0.73105858 0.62245933 0.37754067]


#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [6]:
def hypothesis(theta, X):
    return sigmoid(np.dot(X, theta))

def compute_gradient(theta, X, y):
    m = len(y)
    h = hypothesis(theta, X)

    error = h - y
    gradient = (1 / m) * np.dot(X.T, error)

    return gradient

theta = np.array([0.5, -0.5])
X = np.array([
    [1, 1],
    [1, -1],
    [1, 0],
    [1, 2]
])
y = np.array([1, 0, 1, 0])

grad = compute_gradient(theta, X, y)

print("Градієнт:", grad)

Градієнт: [ 0.05776464 -0.11899431]



#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [8]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    m, n = X.shape

    theta = np.random.randn(n) * 0.01

    for epoch in range(epochs):
        grad = compute_gradient(theta, X, y)
        theta = theta - lr * grad

    return theta

X = np.array([
    [1, 1],
    [1, -1],
    [1, 0],
    [1, 2]
])
y = np.array([1, 0, 1, 0])

final_theta = full_batch_gradient_descent(X, y, lr=0.1, epochs=1000)

print("Навчені параметри theta:", final_theta)

Навчені параметри theta: [ 2.49962820e-10 -1.54485533e-10]


#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [9]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def predict_proba(theta, X):
    z = np.dot(X, theta)
    return sigmoid(z)

def predict(theta, X, threshold=0.5):
    probabilities = predict_proba(theta, X)
    return (probabilities >= threshold).astype(int)

def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

X = np.array([
    [1, 1],
    [1, -1],
    [1, 0],
    [1, 2]
])
y_true = np.array([1, 0, 1, 0])

def full_batch_gradient_descent(X, y, lr=0.1, epochs=1000):
    m, n = X.shape
    np.random.seed(42)
    theta = np.random.randn(n) * 0.01

    for _ in range(epochs):
        h = sigmoid(np.dot(X, theta))
        gradient = (1/m) * np.dot(X.T, (h - y))
        theta -= lr * gradient
    return theta

theta = full_batch_gradient_descent(X, y_true, lr=0.1, epochs=1000)

probabilities = predict_proba(theta, X)

y_pred = predict(theta, X)

acc_score = accuracy(y_true, y_pred)

print("Знайдені параметри theta:", theta)
print("\n1. Передбачені ймовірності:")
print(probabilities)

print("\n2. Передбачені класи:")
print(y_pred)

print("\n3. Реальні класи (для порівняння):")
print(y_true)

print(f"\nТочність моделі (Accuracy): {acc_score}")

Знайдені параметри theta: [ 1.13957334e-10 -7.04295051e-11]

1. Передбачені ймовірності:
[0.5 0.5 0.5 0.5]

2. Передбачені класи:
[1 1 1 0]

3. Реальні класи (для порівняння):
[1 0 1 0]

Точність моделі (Accuracy): 0.75
