### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

vector = np.random.rand(10)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("Вектор:")
print(vector)
print("Розмірність вектора:", vector.shape)
print("\nМатриця:")
print(matrix)
print("Розмірність матриці:", matrix.shape)

Вектор:
[0.72606643 0.16006269 0.49889217 0.58499489 0.64922814 0.88574776
 0.94195527 0.28371176 0.78614276 0.68450334]
Розмірність вектора: (10,)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмірність матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector_plus_10 = np.round(vector + 10, 2)
print("1. Вектор + 10 (округлений):\n", vector_plus_10)

matrix_multiplied = matrix * 2
print("\n2. Матриця * 2:\n", matrix_multiplied)

vector_squared = vector ** 2
print("\n3. Квадрат вектора:\n", vector_squared)

1. Вектор + 10 (округлений):
 [10.73 10.16 10.5  10.58 10.65 10.89 10.94 10.28 10.79 10.68]

2. Матриця * 2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]

3. Квадрат вектора:
 [0.52717246 0.02562006 0.2488934  0.34221903 0.42149718 0.7845491
 0.88727973 0.08049236 0.61802044 0.46854483]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [5]:
result_matrix = np.dot(B, A)
print("1. Результуюча матриця (B @ A):\n", result_matrix)
print("Розмірність:", result_matrix.shape)


result_C = np.dot(result_matrix, C)
print("\n2. Множення на вектор C:\n", result_C)
print("Розмірність:", result_C.shape)

result_D = np.dot(result_matrix, D)
print("\n3. Множення на матрицю D:\n", result_D)
print("Розмірність:", result_D.shape)

1. Результуюча матриця (B @ A):
 [[0.7281 0.5202]
 [0.2034 0.2846]]
Розмірність: (2, 2)

2. Множення на вектор C:
 [[0.5202]
 [0.2846]]
Розмірність: (2, 1)

3. Множення на матрицю D:
 [[0.5202 0.7281]
 [0.2846 0.2034]]
Розмірність: (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [7]:
transposed_result = result_matrix.T
print("1. Транспонована result_matrix:\n", transposed_result)

transposed_vector = vector.T
print("\n2. Транспонований vector:\n", transposed_vector)
print("Shape транспонованого vector:", transposed_vector.shape)

column_vector = np.expand_dims(vector, axis=1)
print("\n3. column_vector (після expand_dims):\n", column_vector)
print("Shape column_vector:", column_vector.shape)

transposed_column_vector = column_vector.T
print("\n4. Транспонований column_vector:\n", transposed_column_vector)
print("Shape транспонованого column_vector:", transposed_column_vector.shape)

1. Транспонована result_matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]

2. Транспонований vector:
 [0.72606643 0.16006269 0.49889217 0.58499489 0.64922814 0.88574776
 0.94195527 0.28371176 0.78614276 0.68450334]
Shape транспонованого vector: (10,)

3. column_vector (після expand_dims):
 [[0.72606643]
 [0.16006269]
 [0.49889217]
 [0.58499489]
 [0.64922814]
 [0.88574776]
 [0.94195527]
 [0.28371176]
 [0.78614276]
 [0.68450334]]
Shape column_vector: (10, 1)

4. Транспонований column_vector:
 [[0.72606643 0.16006269 0.49889217 0.58499489 0.64922814 0.88574776
  0.94195527 0.28371176 0.78614276 0.68450334]]
Shape транспонованого column_vector: (1, 10)
